name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nimo-labs/umake'
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.read_pub_repo }}
        path: 'bootloader'
    - name: umake
      run: |
        cd bootloader
        ../umake
    #- name: arm-none-eabi-gcc
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - run: |
        cd bootloader
        make