name: Dev build

on:
  push:
    branches:
      - dev 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nimo-labs/umake'
    - uses: actions/checkout@v2
      with:
        path: 'bootloader'
        fetch-depth: 0
    - name: umake
      run: |
        cd bootloader
        ../umake.py
    #- name: Compile
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - run: |
        cd bootloader
        make
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}