name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nimo-labs/umake'
    - uses: actions/checkout@v2
      with:
        path: 'bootloader'
    - name: umake
      run: |
        cd bootloader
        ../umake
    #- name: arm-none-eabi-gcc
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - run: |
        cd bootloader
        make

#update version number
    - name: bump version
      run: |
        cd bootloader
        cat version.h
        awk -f bumpver.awk version.h
        cat version.h

    - name: commit version
      uses: test-room-7/action-update-file@v1
      with:
          file-path: bootloader/version.h
          commit-msg: Update version number
          github-token: ${{ secrets.GITHUB_TOKEN }}

#bump release if successful

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"